modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="pausemenuedits" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Pause Menu Edits Mod" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for this  mod goes to Me" #optional

authors="Me, Myself and I" #optional

description='''
Description to be added eventually
I hope
'''
